project_id = "ycounxtgkzyhhaykpaxd"

[functions.generate-airwallex-payment-link]
verify_jwt = true

[functions.send-sms-notification]
verify_jwt = true

[functions.ai-assist]
verify_jwt = true

[functions.extract-document-data]
verify_jwt = true

[functions.docusign-send-contract]
verify_jwt = true

[functions.update-driver-location]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = true

[functions.invite-driver]
verify_jwt = true

[functions.airwallex-webhook]
verify_jwt = false

[functions.send-docusign-contract]
verify_jwt = true

[functions.docusign-webhook]
verify_jwt = false