project_id = "ycounxtgkzyhhaykpaxd"

[functions.generate-airwallex-payment-link]
verify_jwt = true

[functions.send-sms-notification]
verify_jwt = true

[functions.ai-assist]
verify_jwt = true

[functions.extract-document-data]
verify_jwt = true